[package]
name = "csuf_course_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.1"
reqwest = { version = "0.11.23", features = ["blocking"] }
scraper = "0.18.1"
